name: Data Share Deletion ( Restricted to run only from OneMesh Marketplace Integration )
description: "This issue triggers a workflow that will delete Data Share based on input."
title: "Data Share Deletion <-- DO NOT Change this title"
labels: ["data_share_deletion_issue_template"]
assignees: 
  - AbhishekRathod-Sanofi
  - guillaumepiat
  - s2Chris
  - LakshmiYaganti
body:
- type: input
  id: project
  attributes:
    label: "Project Name"
    description: "Mention the existing Project name."
    placeholder: "Example: Project_Name"
  validations:
      required: true
- type: input
  id: provideraccount
  attributes:
    label: "Provider Account Name"
    description: "Mention the existing Provider Account Name."
    placeholder: "Example: EMEA_RND"    
  validations:
      required: true      
