name: Data Share Creation Workflow Dispatch
# Controls when the action will run

on:
  workflow_dispatch:
    inputs:
      PROJECT:
        description: 'Project Name'
        required: true
        type: string
        default: 'Example: Project_Name'
      PROVIDER_ACCOUNT:
        description: 'Provider Account Name'
        required: true
        type: string
        default: 'Example: EMEA_RND'
        ##default: 'Example: FL09027'
      PROVIDER_DB:
        description: 'Provider Database Name'
        required: true
        type: string
        default: 'Example: INSPIRE_DEV'
      PROVIDER_SCHEMA:
        description: 'Provider Schema Name'
        required: true
        type: string
        default: 'Example: Schema_Name'
      PROVIDER_OBJECT:
        description: 'Provider Object Name'
        required: true
        type: string
        default: 'Example: Object_Name or %'      
      CONSUMER_ACCOUNT:
        description: 'Consumer Account Name'
        required: true
        type: string
        default: 'Example: EMEA_SAND'
        ##default: 'Example: ZA90120'
      CONSUMER_ROLE:
        description: 'Consumer Role Name'
        required: true
        type: string
        default: 'Example: Consumer_Role_Name'
      # CONSUMER_RIGHT:
      #   description: 'Consumer Right'
      #   required: true
      #   type: string
      #   default: 'Example: SELECT'      
  
jobs:
  deploy-snowflake-changes-job:
    #environment:
    #  name: assignee
    ##runs-on: [self-hosted, atmos-aws-shared-gh-runner]
    runs-on: [atmos-aws-arc-runner-set]
    ##if: github.event.issue.title  == 'Data Share Creation <-- DO NOT Change this title'
    env:
      REPO_DISPATCH_PAT: ${{ secrets.REPO_DISPATCH_PATOKEN }}
      # ENROLLMENT_EVENT: ${{ github.event_name }}
      # ENROLLMENT_TITLE: ${{ github.event.issue.title }}
      # ENROLLMENT_NUMBER: ${{ github.event.issue.number }}
      # ENROLLMENT_MESSAGE: ${{ github.event.issue.body }}
      # ISSUE_REPO_URL: ${{ github.event.issue.repository_url }}
      # REPO_NAME: ${{ github.event.repository.full_name }}
      # REPO_URL: ${{ github.event.repository.url }}
      INPUT_PROJECT: ${{ inputs.PROJECT }}
      INPUT_PROVIDER_ACCOUNT: ${{ inputs.PROVIDER_ACCOUNT }}
      INPUT_PROVIDER_DB: ${{ inputs.PROVIDER_DB }}
      INPUT_PROVIDER_SCHEMA: ${{ inputs.PROVIDER_SCHEMA }}
      INPUT_PROVIDER_OBJECT: ${{ inputs.PROVIDER_OBJECT }}
      INPUT_CONSUMER_ACCOUNT: ${{ inputs.CONSUMER_ACCOUNT }}
      INPUT_CONSUMER_ROLE: ${{ inputs.CONSUMER_ROLE }}
      #INPUT_CONSUMER_RIGHT: ${{ inputs.CONSUMER_RIGHT }}     
    steps:
      - uses: Sanofi-InnerSource/github-actions-library/setup-root-ca@main
      - run: sudo apt-get update
      - run: sudo apt-get install sudo
      - run: sudo apt-get install -y ca-certificates curl zip
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
           cd "$GITHUB_WORKSPACE/Deployment-Scripts/"
           python -m pip install --upgrade pip
           pip install -r requirements.txt

      - name: Process issue template inputs
        run: |
          #echo 'github.event_name: ${{ github.event_name }}'
          #echo 'github.head_ref: ${{ github.head_ref }}'
          #echo 'github.event.issue.title: ${{ github.event.issue.title }}'
          #echo 'github.event.issue.number: ${{ github.event.issue.number }}'
          #echo 'github.event.issue.body: ${{ github.event.issue.body }}'
          #echo 'github.event.issue.repository_url: ${{ github.event.issue.repository_url }}'
          #echo 'github.event.repository.full_name: ${{ github.event.repository.full_name }}'
          #echo 'github.event.repository.url: ${{ github.event.repository.url }}'
         
          cd "$GITHUB_WORKSPACE/Deployment-Scripts/"
          echo "Executing python script: data_share_creation.py ... " 
          
          python $GITHUB_WORKSPACE/Deployment-Scripts/data_share_creation.py -v
